In [1]:
import numpy as np

In [2]:
li = np.arange(25).reshape(5, 5)
print(li)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
li.ndim

2

In [4]:
np.r_[np.repeat(li, 3), np.tile(li, 3)]

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [5]:
li.shape

(5, 5)

In [6]:
li.dtype.name

'int32'

In [7]:
li.itemsize

4

In [8]:
li.size

25

In [9]:
np.array([6, 7, 8])

array([6, 7, 8])

In [10]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.arange( 10, 50, 5 )

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
np.exp(li)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10]])

In [14]:
np.sqrt(li)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

In [15]:
li.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
li.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
li.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [18]:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[9.91253846 7.94615247 6.85582612]
 [5.10918005 7.15567774 9.87201958]
 [5.30119725 7.81851413 9.29872579]
 [8.55720814 6.27390405 6.75440596]
 [7.29996437 9.06973597 8.05988703]]


In [19]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])